=head1 NAME

check_swap_page - A Nagios plugin to check swap in/out and page iun/out
activities

=head1 SYNOPSIS

check_swap_page --warning-swap 5 --warning-page 10 --critical-swap 10 --critical-page 20 [-v]

=head1 DESCRIPTION

check_swap_page checks swap and page activities. it does B<NOT> check total amount
of available swap storage.

=head2 OPTIONS

=over

=item --warning-swap, --critical-swap

=item --warning-page, --critical-page

=back

=head1 SEE ALSO

check_swap, if you B<really> want to monitor how much swap space left.

=head1 AUTHOR

Tomoyuki Sakurai <tomoyukis@reallyenglish.com>

=head1 LICENSE

Copyright (c) 2012 Tomoyuki Sakurai <tomoyukis@reallyenglish.com>

Permission to use, copy, modify, and distribute this software for any 
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR 
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
